( set arr '(5 1 7 3 2 6 4 9 8) )
( set num2 ( nth i arr ) )
( while ( < i len )
( set num1 ( nth (- i 1) arr ) )
( set num2 ( nth i arr ) ))
( if ( > num1 num2 )
(( set ( nth (- i 1) arr ) num2 )
( set ( nth i arr ) num1 )
( set swapped T ) ) )
( inc i 1)
( print arr )